version: '3'
services:
  log:
    image: trung501/modsecurity-parser:log1.4
    container_name: log
    environment:
      - LOG_PATH=audit.log
    volumes: 
      - ./db:/db
      - /var/log/apache2/modsec:/log
  fe:
    image: flashspys/nginx-static
    container_name: fe
    ports:
      - 5500:80
    volumes: 
      - ./web:/static
  be:
    image: trung501/modsecurity-parser:fastapi1.2
    container_name: be
    ports:
      - 5555:80
    volumes: 
      - ./db:/db
    depends_on:
      - log

    